version: "3.9"
services:
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3310"

  rails:
    build: .
    ports:
      - "3001:3000"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: admin
      DB_DATABASE: app
      DB_PORT: 3306
      DB_HOST: db
    depends_on:
      - db
    volumes:
      - ".:/app"
      - "./config/database.yml:/app/config/database.yml"
volumes:
  db: